maintenance:
  env: backend
server:
  port: 7001
  address: 0.0.0.0

springdoc:
  api-docs:
    enabled: true
  devtools:
    restart:
      exclude: cn/nolaurene/cms/common/sandbox/backend/model/**

image:
  path-prefix: /Users/nolaurence/projects/guoyong-be/image
  host: http://localhost:7001

sandbox:
  backend:
    max-loop: 30
    sse-timeout-ms: 1200000
    max-threads: 10
    worker-url: http://192.168.49.242:7002
    sse-endpoint: /mcp/message/sse
  worker:
    #    baseDirectory: /app
    logDir: /app/logs
    stream-interval: 33
    stream-dir: stream-log
    mcp-port: 7500

llm-client:
  silicon-flow:
    endpoint: https://api.siliconflow.cn/v1
    api-key: 122222222
logging:
  level:
    io.modelcontextprotocol: debug
