spring:
  thymeleaf:
    enabled: false
  application:
    name: case-management-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.49.249:3306/cms?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: nolaurence
    password: 123456
  # session 失效时间
  session:
    timeout: 86400
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 7001

maintenance:
  env: prod

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#  show-actuator: true
##  show-springfox: false
#  api-docs:
#    enabled: false

springdoc:
  show-actuator: true
  api-docs:
    enabled: true
  devtools:
    restart:
      exclude: cn/nolaurene/cms/common/sandbox/backend/model/**

sandbox:
  backend:
    max-loop: 30
    sse-timeout-ms: 1200000
    max-threads: 10
    worker-url: http://worker:7500
    worker-stream-url: http://worker:7002
    worker-ops-url: http://worker:7002
    sse-endpoint: /sse
  worker:
    #    baseDirectory: /app
    playwright-mcp-version: 0.0.39
    logDir: /app/logs
    stream-interval: 33
    stream-dir: stream-log
    mcp-port: 7500

llm-client:
  silicon-flow:
    endpoint: http://192.168.49.253:8080/v1
    api-key: 122222
logging:
  level:
    io.modelcontextprotocol: debug

# disable thymeleaf autoconfig

